services:
  greenmail:
    container_name: "greenmail"
    image: "greenmail/standalone:2.0.0"
    env_file: ".env"
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.smtp.port=${SMTP_SERVER_PORT} -Dgreenmail.imaps.port=${IMAPS_SERVER_PORT} -Dgreenmail.users=${SMTP_USER}:${SMTP_PASSWORD}@localhost,${IMAP_USER}:${IMAP_PASSWORD}@localhost -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.verbose"
      JAVA_OPTS: "-Djava.net.preferIPv4Stack=true -Xmx512m"
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 1s
      retries: 3

  smtp_client:
    container_name: "smtp_client"
    command: "smtp_client"
    build: smtp_client
    env_file: ".env"
    ports:
      - "${SMTP_CLIENT_PORT}:${SMTP_CLIENT_PORT}"
    depends_on:
      greenmail:
        condition: service_healthy


  imap_client:
    container_name: "imap_client"
    command: "imap_client"
    build: 
      context: .
      dockerfile: ./imap_client/Dockerfile
    env_file: ".env"
    ports:
      - "${IMAP_CLIENT_PORT}:${IMAP_CLIENT_PORT}"
    depends_on:
      greenmail:
        condition: service_healthy
